server:
  port: ${PORT:${SERVERS_PORT:0}}

spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_auth2
    username: root
    password: 12345

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8095/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

jwt:
  secret: mySuperSecretKeyForJwtGeneration_2025_ChangeThisNow!

resilience4j:
  circuitbreaker:
    instances:
      personaService:
        register-health-indicator: true
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s