export const END_POINTS = {
  personas: '/personas',
  login: '/auth/login',
  registrar: '/auth/create',
  camposextraidos_listar: '/ocr/listar',
  camposextraidos_eliminar: '/ocr/eliminar',
  camposestraidos_editar: '/ocr/actualizar',
  camposetraidos_crear: '/ocr/convertir',
  camposexportar: '/ocr/exportdb/id',
  viewpdf: '/ocr/viewpdf/filename',
  persons_id: '/personas/id',
  //persons_put: '/personas/id',
  persons_post: '/personas/id',
  persons_delet: '/personas/eliminar/id',

  tramites_listar: '/api/tramites',
  tramite_id: '/api/tramites',
  tramite_crear: '/tramites/creartra',
  tramite_eliminar: '/api/tramites',
  tramite_completo: '/api/tramites/completo',
  tramite_tipos_documento: '//tramites/crear',
  tramite_actualizar_estado: '/api/tramites',
  documento_listar: '/api/tramites',
  oficina_listar: '/oficinas',
  login_cretae: '/auth/create'
};
